In [20]:
from pandas import DataFrame, read_csv

In [21]:
df_original: DataFrame = read_csv("data/metrics-reranking-all-original.csv")
df_original

,name,name_index,nDCG@5 rel.,nDCG@5 rel. test,nDCG@5 qual.,nDCG@5 qual. test,"rKL@5(FIRST,SECOND,NEUTRAL)","rKL@5(FIRST,SECOND,NEUTRAL) test","rND@5(FIRST,SECOND,NEUTRAL)","rND@5(FIRST,SECOND,NEUTRAL) test","rRD@5(FIRST,SECOND,NEUTRAL)","rRD@5(FIRST,SECOND,NEUTRAL) test",alpha_nDCG@5 rel.,alpha_nDCG@5 rel. test,alpha_nDCG@5 qual.,alpha_nDCG@5 qual. test
0,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.547,NaN,0.570,NaN,0.771,NaN,0.857,NaN,0.864,NaN,0.533,NaN,0.533,NaN
1,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.546,NaN,0.570,NaN,0.771,NaN,0.857,NaN,0.864,NaN,0.533,NaN,0.533,NaN
2,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,3,0.546,NaN,0.570,NaN,0.771,NaN,0.857,NaN,0.864,NaN,0.533,NaN,0.533,NaN
3,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,4,0.546,NaN,0.570,NaN,0.771,NaN,0.857,NaN,0.864,NaN,0.533,NaN,0.533,NaN
4,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.636,NaN,0.764,NaN,0.784,NaN,0.846,NaN,0.856,NaN,0.594,NaN,0.594,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Olivier-Armstrong tfid_arg_similarity + stance...,4,0.490,NaN,0.581,NaN,0.797,NaN,0.872,NaN,0.878,NaN,0.510,NaN,0.510,NaN
100,Puss-in-Boots BM25-Baseline,1,0.469,NaN,0.476,NaN,0.865,NaN,0.881,NaN,0.898,NaN,0.465,NaN,0.465,NaN
101,Puss-in-Boots BM25-Baseline + stance-first@5,2,0.469,NaN,0.476,NaN,0.865,NaN,0.881,NaN,0.898,NaN,0.465,NaN,0.465,NaN
102,Puss-in-Boots BM25-Baseline + alternating-stan...,3,0.469,NaN,0.476,NaN,0.865,NaN,0.881,NaN,0.898,NaN,0.465,NaN,0.465,NaN
103,Puss-in-Boots BM25-Baseline + stance-first@5 +...,4,0.469,NaN,0.476,NaN,0.865,NaN,0.881,NaN,0.898,NaN,0.465,NaN,0.465,NaN

In [22]:
df_gt: DataFrame = read_csv("data/metrics-reranking-all-ground-truth.csv")
df_gt

,name,name_index,nDCG@5 rel.,nDCG@5 rel. test,nDCG@5 qual.,nDCG@5 qual. test,"rKL@5(FIRST,SECOND,NEUTRAL)","rKL@5(FIRST,SECOND,NEUTRAL) test","rND@5(FIRST,SECOND,NEUTRAL)","rND@5(FIRST,SECOND,NEUTRAL) test","rRD@5(FIRST,SECOND,NEUTRAL)","rRD@5(FIRST,SECOND,NEUTRAL) test",alpha_nDCG@5 rel.,alpha_nDCG@5 rel. test,alpha_nDCG@5 qual.,alpha_nDCG@5 qual. test
0,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.547,"2,4",0.570,"2,4",0.771,NaN,0.857,NaN,0.864,NaN,0.533,"2,3,4",0.533,"2,3,4"
1,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.576,"1,3",0.599,"1,3",0.813,NaN,0.862,NaN,0.884,NaN,0.584,"1,3",0.584,"1,3"
2,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,3,0.549,"2,4",0.571,"2,4",0.758,NaN,0.836,NaN,0.880,NaN,0.541,"1,2,4",0.541,"1,2,4"
3,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,4,0.575,"1,3",0.599,"1,3",0.805,NaN,0.852,NaN,0.900,NaN,0.587,"1,3",0.587,"1,3"
4,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.636,"2,4",0.764,"2,4",0.784,NaN,0.846,NaN,0.856,NaN,0.594,"2,3,4",0.594,"2,3,4"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Olivier-Armstrong tfid_arg_similarity + ground...,4,0.548,"1,3",0.625,"1,3",0.813,NaN,0.867,NaN,0.915,NaN,0.591,"1,3",0.591,"1,3"
100,Puss-in-Boots BM25-Baseline,1,0.469,"2,3,4",0.476,"2,4",0.865,NaN,0.881,NaN,0.898,NaN,0.465,"2,3,4",0.465,"2,3,4"
101,Puss-in-Boots BM25-Baseline + ground-truth + s...,2,0.517,"1,3",0.505,"1,3",0.875,NaN,0.872,NaN,0.921,NaN,0.537,"1,3",0.537,"1,3"
102,Puss-in-Boots BM25-Baseline + ground-truth + a...,3,0.476,"1,2,4",0.479,"2,4",0.855,NaN,0.869,NaN,0.920,NaN,0.478,"1,2,4",0.478,"1,2,4"
103,Puss-in-Boots BM25-Baseline + ground-truth + s...,4,0.516,"1,3",0.504,"1,3",0.866,NaN,0.859,NaN,0.920,NaN,0.540,"1,3",0.540,"1,3"

In [23]:
df_gpt: DataFrame = read_csv("data/metrics-reranking-all-gpt3.csv")
df_gpt

,name,name_index,nDCG@5 rel.,nDCG@5 rel. test,nDCG@5 qual.,nDCG@5 qual. test,"rKL@5(FIRST,SECOND,NEUTRAL)","rKL@5(FIRST,SECOND,NEUTRAL) test","rND@5(FIRST,SECOND,NEUTRAL)","rND@5(FIRST,SECOND,NEUTRAL) test","rRD@5(FIRST,SECOND,NEUTRAL)","rRD@5(FIRST,SECOND,NEUTRAL) test",alpha_nDCG@5 rel.,alpha_nDCG@5 rel. test,alpha_nDCG@5 qual.,alpha_nDCG@5 qual. test
0,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.547,NaN,0.570,NaN,0.771,NaN,0.857,NaN,0.864,NaN,0.533,NaN,0.533,NaN
1,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.559,NaN,0.577,NaN,0.781,NaN,0.861,NaN,0.867,NaN,0.545,NaN,0.545,NaN
2,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,3,0.547,NaN,0.570,NaN,0.768,NaN,0.853,NaN,0.852,NaN,0.535,NaN,0.535,NaN
3,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,4,0.559,NaN,0.576,NaN,0.781,NaN,0.861,NaN,0.867,NaN,0.546,NaN,0.546,NaN
4,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.636,NaN,0.764,NaN,0.784,NaN,0.846,NaN,0.856,NaN,0.594,NaN,0.594,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Olivier-Armstrong tfid_arg_similarity + gpt3-t...,4,0.517,1,0.607,"1,3",0.848,NaN,0.862,NaN,0.903,NaN,0.548,NaN,0.548,NaN
100,Puss-in-Boots BM25-Baseline,1,0.469,"2,4",0.476,NaN,0.865,NaN,0.881,NaN,0.898,NaN,0.465,NaN,0.465,NaN
101,Puss-in-Boots BM25-Baseline + gpt3-tsv + stanc...,2,0.492,"1,3",0.487,NaN,0.878,NaN,0.877,NaN,0.895,NaN,0.495,NaN,0.495,NaN
102,Puss-in-Boots BM25-Baseline + gpt3-tsv + alter...,3,0.469,"2,4",0.479,NaN,0.865,NaN,0.881,NaN,0.898,NaN,0.467,NaN,0.467,NaN
103,Puss-in-Boots BM25-Baseline + gpt3-tsv + stanc...,4,0.492,"1,3",0.487,NaN,0.878,NaN,0.877,NaN,0.895,NaN,0.495,NaN,0.495,NaN

In [24]:
for k, df in {"original": df_original, "ground truth": df_gt, "GPT-3": df_gpt}.items():
    df = df[df["name"].str.endswith(" + stance-first@5 + alternating-stance@5")]
    for cols in [
        ["nDCG@5 rel.", "nDCG@5 qual."],
        ["alpha_nDCG@5 rel.", "alpha_nDCG@5 qual."],
    ]:
        df2 = df.copy()
        for col in cols:
            df2 = df2[df2[f"{col} test"].notna()]
            if len(df2) > 0:
                df2 = df2[df2[f"{col} test"].str.contains("1")]
        print(k, cols, len(df2) / 26)

original ['nDCG@5 rel.', 'nDCG@5 qual.'] 0.0
original ['alpha_nDCG@5 rel.', 'alpha_nDCG@5 qual.'] 0.0
ground truth ['nDCG@5 rel.', 'nDCG@5 qual.'] 0.9615384615384616
ground truth ['alpha_nDCG@5 rel.', 'alpha_nDCG@5 qual.'] 1.0
GPT-3 ['nDCG@5 rel.', 'nDCG@5 qual.'] 0.19230769230769232
GPT-3 ['alpha_nDCG@5 rel.', 'alpha_nDCG@5 qual.'] 0.15384615384615385

In [25]:
df_f1: DataFrame = read_csv("data/metrics-reranking-all-f1.csv")
df_f1

,name,name_index,nDCG@5 rel.,nDCG@5 rel. test,nDCG@5 qual.,nDCG@5 qual. test,F1,F1 test,"rKL@5(FIRST,SECOND,NEUTRAL)","rKL@5(FIRST,SECOND,NEUTRAL) test","rND@5(FIRST,SECOND,NEUTRAL)","rND@5(FIRST,SECOND,NEUTRAL) test","rRD@5(FIRST,SECOND,NEUTRAL)","rRD@5(FIRST,SECOND,NEUTRAL) test",alpha_nDCG@5 rel.,alpha_nDCG@5 rel. test,alpha_nDCG@5 qual.,alpha_nDCG@5 qual. test
0,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.547,2,0.570,2,0.156,"2,3,4,5,6",0.771,NaN,0.857,NaN,0.864,NaN,0.533,2,0.533,2
1,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.575,1,0.599,1,1.000,"1,3,4,5,6",0.805,NaN,0.852,NaN,0.900,NaN,0.587,1,0.587,1
2,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,3,0.564,NaN,0.595,NaN,0.947,"1,2,4,5,6",0.779,NaN,0.835,NaN,0.882,NaN,0.557,NaN,0.557,NaN
3,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,4,0.561,NaN,0.597,NaN,0.901,"1,2,3,5,6",0.764,NaN,0.832,NaN,0.884,NaN,0.560,NaN,0.560,NaN
4,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,5,0.559,NaN,0.587,NaN,0.850,"1,2,3,4,6",0.778,NaN,0.835,NaN,0.877,NaN,0.555,NaN,0.555,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Puss-in-Boots BM25-Baseline + ground-truth + s...,2,0.516,1,0.504,1,1.000,"1,3,4,5,6",0.866,NaN,0.859,NaN,0.920,NaN,0.540,1,0.540,1
152,Puss-in-Boots BM25-Baseline + ground-truth(F1<...,3,0.518,"1,5",0.509,"5,6",0.947,"1,2,4,5,6",0.861,NaN,0.856,NaN,0.910,NaN,0.540,1,0.540,1
153,Puss-in-Boots BM25-Baseline + ground-truth(F1<...,4,0.495,NaN,0.492,NaN,0.896,"1,2,3,5,6",0.815,NaN,0.845,NaN,0.898,NaN,0.509,NaN,0.509,NaN
154,Puss-in-Boots BM25-Baseline + ground-truth(F1<...,5,0.484,3,0.480,3,0.832,"1,2,3,4,6",0.842,NaN,0.842,NaN,0.903,NaN,0.491,NaN,0.491,NaN
155,Puss-in-Boots BM25-Baseline + ground-truth(F1<...,6,0.493,NaN,0.482,3,0.783,"1,2,3,4,5",0.805,NaN,0.844,NaN,0.892,NaN,0.498,NaN,0.498,NaN

In [26]:
eval = {}
for cols in [
    ("nDCG@5 rel.", "nDCG@5 qual."),
    ("alpha_nDCG@5 rel.", "alpha_nDCG@5 qual."),
]:
    eval[cols] = {}
    df1 = df_f1.copy()
    for f1 in [1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3]:
        df2 = df1.copy()
        f1_str = f"(F1<={f1:.2f})" if f1 < 1 else ""
        gt_string = f" + ground-truth{f1_str} + "
        df2 = df2[df2["name"].str.contains(gt_string, regex=False)]
        for col in cols:
            df2 = df2[df2[f"{col} test"].notna()]
            if len(df2) > 0:
                df2 = df2[df2[f"{col} test"].str.contains("1")]
        eval[cols][f1] = len(df2)
df_eval_f1 = DataFrame([
    {
        "cols": ", ".join(cols),
        "f1": f1,
        "n": n,
    }
    for cols, evals in eval.items()
    for f1, n in evals.items()
])
df_eval_f1

                                     cols   f1   n
0               nDCG@5 rel., nDCG@5 qual.  1.0  21
1               nDCG@5 rel., nDCG@5 qual.  0.9   3
2               nDCG@5 rel., nDCG@5 qual.  0.8   0
3               nDCG@5 rel., nDCG@5 qual.  0.7   0
4               nDCG@5 rel., nDCG@5 qual.  0.6   0
5               nDCG@5 rel., nDCG@5 qual.  0.5   0
6               nDCG@5 rel., nDCG@5 qual.  0.4   0
7               nDCG@5 rel., nDCG@5 qual.  0.3   0
8   alpha_nDCG@5 rel., alpha_nDCG@5 qual.  1.0  26
9   alpha_nDCG@5 rel., alpha_nDCG@5 qual.  0.9  10
10  alpha_nDCG@5 rel., alpha_nDCG@5 qual.  0.8   0
11  alpha_nDCG@5 rel., alpha_nDCG@5 qual.  0.7   0
12  alpha_nDCG@5 rel., alpha_nDCG@5 qual.  0.6   0
13  alpha_nDCG@5 rel., alpha_nDCG@5 qual.  0.5   0
14  alpha_nDCG@5 rel., alpha_nDCG@5 qual.  0.4   0
15  alpha_nDCG@5 rel., alpha_nDCG@5 qual.  0.3   0