In [12]:
from math import nan

from pandas import DataFrame, read_csv
from re import compile

In [13]:
df_original: DataFrame = read_csv("data/metrics-reranking-all-original.csv")
df_original["run"] = df_original["name"].apply(lambda name: name.split(" + ")[0])
df_original["team"] = df_original["run"].apply(lambda run: run.split(" ")[0])
df_original

,name,name_index,nDCG@5 rel.,nDCG@5 rel. test,nDCG@5 qual.,nDCG@5 qual. test,alpha_nDCG@5 rel.,alpha_nDCG@5 rel. test,alpha_nDCG@5 qual.,alpha_nDCG@5 qual. test,rKL@5,rKL@5 test,rND@5,rND@5 test,rRD@5,rRD@5 test,run,team
0,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.547,NaN,0.570,NaN,0.533,NaN,0.533,NaN,0.752,NaN,0.845,NaN,0.863,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
1,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.546,NaN,0.570,NaN,0.533,NaN,0.533,NaN,0.752,NaN,0.845,NaN,0.863,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
2,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,3,0.546,NaN,0.570,NaN,0.533,NaN,0.533,NaN,0.752,NaN,0.845,NaN,0.863,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
3,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.636,NaN,0.764,NaN,0.594,NaN,0.594,NaN,0.769,NaN,0.835,NaN,0.856,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
4,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.636,NaN,0.764,NaN,0.594,NaN,0.594,NaN,0.769,NaN,0.835,NaN,0.856,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Olivier-Armstrong tfid_arg_similarity + stance...,2,0.492,NaN,0.583,NaN,0.512,NaN,0.512,NaN,0.786,NaN,0.854,NaN,0.866,NaN,Olivier-Armstrong tfid_arg_similarity,Olivier-Armstrong
74,Olivier-Armstrong tfid_arg_similarity + stance...,3,0.489,NaN,0.581,NaN,0.509,NaN,0.509,NaN,0.786,NaN,0.857,NaN,0.864,NaN,Olivier-Armstrong tfid_arg_similarity,Olivier-Armstrong
75,Puss-in-Boots BM25-Baseline,1,0.469,NaN,0.476,NaN,0.465,NaN,0.465,NaN,0.855,NaN,0.887,NaN,0.895,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots
76,Puss-in-Boots BM25-Baseline + stance-first@5,2,0.469,NaN,0.476,NaN,0.465,NaN,0.465,NaN,0.855,NaN,0.887,NaN,0.895,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots
77,Puss-in-Boots BM25-Baseline + stance-first@5 +...,3,0.469,NaN,0.476,NaN,0.465,NaN,0.465,NaN,0.855,NaN,0.887,NaN,0.895,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots

,name,name_index,nDCG@5 rel.,nDCG@5 rel. test,nDCG@5 qual.,nDCG@5 qual. test,alpha_nDCG@5 rel.,alpha_nDCG@5 rel. test,alpha_nDCG@5 qual.,alpha_nDCG@5 qual. test,rKL@5,rKL@5 test,rND@5,rND@5 test,rRD@5,rRD@5 test,run,team
0,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.547,NaN,0.570,NaN,0.533,NaN,0.533,NaN,0.752,NaN,0.845,NaN,0.863,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
1,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.546,NaN,0.570,NaN,0.533,NaN,0.533,NaN,0.752,NaN,0.845,NaN,0.863,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
2,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,3,0.546,NaN,0.570,NaN,0.533,NaN,0.533,NaN,0.752,NaN,0.845,NaN,0.863,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
3,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.636,NaN,0.764,NaN,0.594,NaN,0.594,NaN,0.769,NaN,0.835,NaN,0.856,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
4,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.636,NaN,0.764,NaN,0.594,NaN,0.594,NaN,0.769,NaN,0.835,NaN,0.856,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Olivier-Armstrong tfid_arg_similarity + stance...,2,0.492,NaN,0.583,NaN,0.512,NaN,0.512,NaN,0.786,NaN,0.854,NaN,0.866,NaN,Olivier-Armstrong tfid_arg_similarity,Olivier-Armstrong
74,Olivier-Armstrong tfid_arg_similarity + stance...,3,0.489,NaN,0.581,NaN,0.509,NaN,0.509,NaN,0.786,NaN,0.857,NaN,0.864,NaN,Olivier-Armstrong tfid_arg_similarity,Olivier-Armstrong
75,Puss-in-Boots BM25-Baseline,1,0.469,NaN,0.476,NaN,0.465,NaN,0.465,NaN,0.855,NaN,0.887,NaN,0.895,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots
76,Puss-in-Boots BM25-Baseline + stance-first@5,2,0.469,NaN,0.476,NaN,0.465,NaN,0.465,NaN,0.855,NaN,0.887,NaN,0.895,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots
77,Puss-in-Boots BM25-Baseline + stance-first@5 +...,3,0.469,NaN,0.476,NaN,0.465,NaN,0.465,NaN,0.855,NaN,0.887,NaN,0.895,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots

In [3]:
df_gt: DataFrame = read_csv("data/metrics-reranking-all-ground-truth.csv")
df_gt["run"] = df_gt["name"].apply(lambda name: name.split(" + ")[0])
df_gt["team"] = df_gt["run"].apply(lambda run: run.split(" ")[0])
df_gt

,name,name_index,nDCG@5 rel.,nDCG@5 rel. test,nDCG@5 qual.,nDCG@5 qual. test,alpha_nDCG@5 rel.,alpha_nDCG@5 rel. test,alpha_nDCG@5 qual.,alpha_nDCG@5 qual. test,rKL@5,rKL@5 test,rND@5,rND@5 test,rRD@5,rRD@5 test,run,team
0,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.547,"2,3",0.570,"2,3",0.533,"2,3",0.533,"2,3",0.752,NaN,0.845,NaN,0.863,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
1,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.576,1,0.599,1,0.584,1,0.584,1,0.792,NaN,0.847,NaN,0.880,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
2,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,3,0.575,1,0.597,1,0.587,1,0.587,1,0.786,NaN,0.834,NaN,0.890,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
3,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.636,"2,3",0.764,"2,3",0.594,"2,3",0.594,"2,3",0.769,NaN,0.835,NaN,0.856,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
4,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.672,1,0.792,1,0.651,"1,3",0.651,"1,3",0.830,NaN,0.857,NaN,0.873,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Olivier-Armstrong tfid_arg_similarity + ground...,2,0.548,1,0.624,1,0.586,1,0.586,1,0.807,NaN,0.839,NaN,0.892,NaN,Olivier-Armstrong tfid_arg_similarity,Olivier-Armstrong
74,Olivier-Armstrong tfid_arg_similarity + ground...,3,0.548,1,0.625,1,0.590,1,0.590,1,0.807,NaN,0.838,NaN,0.899,NaN,Olivier-Armstrong tfid_arg_similarity,Olivier-Armstrong
75,Puss-in-Boots BM25-Baseline,1,0.469,"2,3",0.476,"2,3",0.465,"2,3",0.465,"2,3",0.855,NaN,0.887,NaN,0.895,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots
76,Puss-in-Boots BM25-Baseline + ground-truth + s...,2,0.517,1,0.505,1,0.537,1,0.537,1,0.873,NaN,0.872,NaN,0.918,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots
77,Puss-in-Boots BM25-Baseline + ground-truth + s...,3,0.516,1,0.504,1,0.540,1,0.540,1,0.863,NaN,0.858,NaN,0.913,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots

In [4]:
df_gpt: DataFrame = read_csv("data/metrics-reranking-all-gpt3.csv")
df_gpt["run"] = df_gpt["name"].apply(lambda name: name.split(" + ")[0])
df_gpt["team"] = df_gpt["run"].apply(lambda run: run.split(" ")[0])
df_gpt

,name,name_index,nDCG@5 rel.,nDCG@5 rel. test,nDCG@5 qual.,nDCG@5 qual. test,alpha_nDCG@5 rel.,alpha_nDCG@5 rel. test,alpha_nDCG@5 qual.,alpha_nDCG@5 qual. test,rKL@5,rKL@5 test,rND@5,rND@5 test,rRD@5,rRD@5 test,run,team
0,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.547,NaN,0.570,NaN,0.533,NaN,0.533,NaN,0.752,NaN,0.845,NaN,0.863,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
1,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.559,NaN,0.577,NaN,0.545,NaN,0.545,NaN,0.762,NaN,0.850,NaN,0.866,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
2,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,3,0.559,NaN,0.576,NaN,0.546,NaN,0.546,NaN,0.762,NaN,0.850,NaN,0.866,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
3,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,1,0.636,NaN,0.764,NaN,0.594,NaN,0.594,NaN,0.769,NaN,0.835,NaN,0.856,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
4,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,2,0.648,NaN,0.771,NaN,0.625,NaN,0.625,NaN,0.764,NaN,0.824,NaN,0.842,NaN,Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_fals...,Aldo-Nadi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Olivier-Armstrong tfid_arg_similarity + gpt3-t...,2,0.517,1,0.607,1,0.547,1,0.547,1,0.824,NaN,0.862,NaN,0.893,NaN,Olivier-Armstrong tfid_arg_similarity,Olivier-Armstrong
74,Olivier-Armstrong tfid_arg_similarity + gpt3-t...,3,0.517,1,0.607,1,0.548,1,0.548,1,0.824,NaN,0.862,NaN,0.893,NaN,Olivier-Armstrong tfid_arg_similarity,Olivier-Armstrong
75,Puss-in-Boots BM25-Baseline,1,0.469,"2,3",0.476,NaN,0.465,NaN,0.465,NaN,0.855,NaN,0.887,NaN,0.895,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots
76,Puss-in-Boots BM25-Baseline + gpt3-tsv + stanc...,2,0.492,1,0.487,NaN,0.495,NaN,0.495,NaN,0.852,NaN,0.885,NaN,0.890,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots
77,Puss-in-Boots BM25-Baseline + gpt3-tsv + stanc...,3,0.492,1,0.487,NaN,0.495,NaN,0.495,NaN,0.852,NaN,0.885,NaN,0.890,NaN,Puss-in-Boots BM25-Baseline,Puss-in-Boots

In [5]:
cols_combinations = [
    ["nDCG@5 rel."],
    ["nDCG@5 qual."],
    ["nDCG@5 rel.", "nDCG@5 qual."],
    ["alpha_nDCG@5 rel."],
    ["alpha_nDCG@5 qual."],
    ["alpha_nDCG@5 rel.", "alpha_nDCG@5 qual."],
]

In [6]:
eval_data = []

In [7]:
for labels, df_labels in {"original": df_original, "ground truth": df_gt, "GPT-3": df_gpt}.items():
    df_labels = df_labels[df_labels["name"].str.endswith(" + stance-first@5 + alternating-stance@5")]
    for cols in cols_combinations:
        df_tmp = df_labels.copy()
        for col in cols:
            df_tmp = df_tmp[df_tmp[f"{col} test"].notna()]
            if len(df_tmp) > 0:
                df_tmp = df_tmp[df_tmp[f"{col} test"].str.contains("1")]
        eval_data.append({
            "labels": labels,
            "cols": " & ".join(cols),
            "num_significant": len(df_tmp),
            "prop_significant": len(df_tmp) / len(df_labels["run"].unique()),
        })

In [8]:
# def target_f1(name: str) -> float:
#     parts = name.split(" + ")
#     for part in parts:
#         if part.startswith("randomize"):
#             match = compile(r"randomize\(F1<=(.*)\)").match(part)
#             if not match:
#                 return 1.0
#             return float(match.group(1))
#     return nan

In [9]:
# df_f1: DataFrame = read_csv("data/metrics-reranking-all-f1.perquery.csv")
# df_f1["run"] = df_f1["name"].apply(lambda name: name.split(" + ")[0])
# df_f1["team"] = df_f1["run"].apply(lambda run: run.split(" ")[0])
# df_f1["target_f1"] = df_f1["name"].apply(target_f1).fillna(1)
# df_f1

In [10]:
# for cols in cols_combinations:
#     for f1 in df_f1["target_f1"].unique():
#         df_tmp = df_f1.copy()
#         df_tmp = df_tmp[df_tmp["target_f1"] == f1]
#         for col in cols:
#             df_tmp = df_tmp[df_tmp[f"{col} test"].notna()]
#             if len(df_tmp) > 0:
#                 df_tmp = df_tmp[df_tmp[f"{col} test"].str.contains("1")]
#
#         df_tmp = df_tmp.groupby("run").first().reset_index()
#
#         eval_data.append({
#             "labels": f"randomized F1<={f1:.2f}",
#             "cols": " & ".join(cols),
#             "num_significant": len(df_tmp),
#             "prop_significant": len(df_tmp) / len(df_f1["run"].unique()),
#         })

In [11]:
df_eval = DataFrame(eval_data)
df_eval.to_csv("data/num_significant.csv")
df_eval

,labels,cols,num_significant,prop_significant
0,original,nDCG@5 rel.,0,0.000000
1,original,nDCG@5 qual.,0,0.000000
2,original,nDCG@5 rel. & nDCG@5 qual.,0,0.000000
3,original,alpha_nDCG@5 rel.,0,0.000000
4,original,alpha_nDCG@5 qual.,0,0.000000
5,original,alpha_nDCG@5 rel. & alpha_nDCG@5 qual.,0,0.000000
6,ground truth,nDCG@5 rel.,26,1.000000
7,ground truth,nDCG@5 qual.,25,0.961538
8,ground truth,nDCG@5 rel. & nDCG@5 qual.,25,0.961538
9,ground truth,alpha_nDCG@5 rel.,26,1.000000
10,ground truth,alpha_nDCG@5 qual.,26,1.000000
11,ground truth,alpha_nDCG@5 rel. & alpha_nDCG@5 qual.,26,1.000000
12,GPT-3,nDCG@5 rel.,12,0.461538
13,GPT-3,nDCG@5 qual.,14,0.538462
14,GPT-3,nDCG@5 rel. & nDCG@5 qual.,9,0.346154
15,GPT-3,alpha_nDCG@5 rel.,5,0.192308
16,GPT-3,alpha_nDCG@5 qual.,5,0.192308
17,GPT-3,alpha_nDCG@5 rel. & alpha_nDCG@5 qual.,5,0.192308